### ISSUE TITLE
Video download currently 404s

### ISSUE THREAD

**Issue by chrisjbillington** [ProstoSanja/place-2022#1]
The latest video download:

https://place.thatguyalex.com/36_hours_full.mp4

Is giving me a 404:

![image](https://user-images.githubusercontent.com/1044087/161406541-f347aa63-74c1-4c24-9e8b-5cff804bf09d.png)

It it supposed to be committed to the git repo? I see the 24 hour video is, but the 36h one is not.

**Comment by ProstoSanja** [comment]
all fixed @chrisjbillington it was me forgetting to copy the file.

Video is not on github because the sizes are too big, so just download it from the website.

**Comment by ProstoSanja** [comment]
it is also the new link, 48 hours now 👌

**Comment by chrisjbillington** [comment]
Much appreciated!
