### ISSUE TITLE
GTEestiProDisplay-Regular.ttf not included

### ISSUE THREAD

**Issue by jarednthomas** [ProstoSanja/place-2022#3]
Had to comment out your font-face css since that file wasn't uploaded; You had it in your gitignore. Works just fine without it though; great work!

**Comment by ProstoSanja** [comment]
Hey, that is intentional. This is a liecensed font, so i am not posting it to the public repo. It is still available when viewing the website, as it is present on the server. 
I have also setup a proper fallback, so this shouldn't be an issue if you are running locally.

**Comment by RndUsername** [comment]
The fallback doesn't work for me. I run it locally and get the an "Module not found: Error: Can't resolve 'icons/GTEestiProDisplay-Regular.ttf' in 'C:\...\place-2022\src'" error, so it can't be compiled.

**Comment by jarednthomas** [comment]
Yeah I figured, but that wasn't noted in the readme and it is breaking without it, as per the comment above me. @RndUsername: comment out or remove the declared font in the css and it will fallback.

**Comment by ProstoSanja** [comment]
Ah, didn't realize it failed compilation without that. Need to create a fallback for build to work 👍

**Comment by ProstoSanja** [comment]
fixed
