### ISSUE TITLE
Torrent file?

### ISSUE THREAD

**Issue by ryleu** [ProstoSanja/place-2022#6]
I would love to be able to help take some load off of your server by seeding a torrent. Is an official torrent file in the works?

**Comment by ProstoSanja** [comment]
Not rn, i don't have time nor the effort to seed it.
+I'm pretty sure using gCloud for torrent is against ToS.

Servers are currently doing absolutely fine, so just download directly.

**Comment by ProstoSanja** [comment]
#8

**Comment by ProstoSanja** [comment]
back up and running, torrent available, please help seed :) @ryleu 
and sorry for being mistaken in the first place
